### ISSUE TITLE
[TODO]Action System

### ISSUE THREAD

**Issue by HaoDrang** [HaoDrang/GalFighter#2]
- [ ] Basic System with different handlers to handle All actions
  PS: target and action should be separated
- [ ] Build Action handlers
- [ ] Build Animation Handlers
- [ ] Make sure we can call actions by configure them in json files.
