### ISSUE TITLE
[TODO] Sound System

### ISSUE THREAD

**Issue by HaoDrang** [HaoDrang/GalFighter#3]
- [ ] can play BGM
- [ ] can play sound effect PROPERLY ( can be multiple )
- [ ] can change BGM 
- [ ] can change BGM and play sound effect by action keyword
