### ISSUE TITLE
[TODO] Line Controller

### ISSUE THREAD

**Issue by HaoDrang** [HaoDrang/GalFighter#5]
- [ ] different type of words animation
  (one by one, line by line, all, etc.)
- [ ] Line Rectangle fade in & out animation
- [ ] Rectangle can change color and image
- [ ] Then, can be changed by json action config
