### ISSUE TITLE
[TODO]Storage System

### ISSUE THREAD

**Issue by HaoDrang** [HaoDrang/GalFighter#6]
- [ ] Save current game stat and Chapter and part,
- [ ] Load data and setup to game
- [ ] screen capture as saved slot image
